spring:
    config:
        activate:
            on-profile: dev

    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

logging:
    level:
        org:
            springframework: INFO

external:
    youth-policy:
        base-url: ${YOUTH_POLICY_API_URL}
        api-key: ${YOUTH_POLICY_API_KEY}